### ISSUE TITLE
[Enhancement] Add certificate alias as cert variable

### ISSUE THREAD

**Issue by dfranzi** [fastlane/cert#10]
Part of my current workflow requires the certificate alias. It'd be great to add another cert variable for storing this after either locating or installing the certificate.

I believe this could be achieved by using the java keytool to list the certificates and grepping for the current alias containing the CER_CERTIFICATE_ID that was just used. 

e.g. 
```
keytool -v -storetype KeychainStore -providerName Apple -keystore NONE -storepass NONE -list | grep ENV["CER_CERTIFICATE_ID]
```

Running the above yields:
```
Alias name: iphone developer: user name (certificate_id)
```

**Comment by KrauseFx** [comment]
I have never worked with aliases, what are you using them for?

**Comment by dfranzi** [comment]
Our project is using a third-party engine for cross-compilation that does not use XCode for the build process. The tools provided expect either a .p12 file, which would require manual steps and splitting any fastlane work into separate actions, or the alias of the certificate in the keychain to do the signing.

**Comment by fastlane-bot-helper** [comment]
This issue was migrated to https://github.com/fastlane/fastlane/issues/1812. Please post all further comments there.

`fastlane` is now a mono repo, you can read more about the change in our [blog post](https://krausefx.com/blog/our-goal-to-unify-fastlane-tools). All tools are now available in the [fastlane main repo](https://github.com/fastlane/fastlane) :rocket:
